language: node_js
before_script:
  - cp config.json.default config.json
  - npm install -g bower gulp
  - bower install
  - npm install
script:
  - gulp

addons:
  sauce_connect:
    username: "nschloe"
    secure: "JDDow7m6421BR4jRz/RQesNGq/aVgNCGe4lvfh4WNeRXbsFUXhTR+A/pRfBJO4peaUCurFXuz0iw/z98jwteHwxZIdihsTTNmjdU1fR1IPVZy9pddX49LPecVqImN9R5+YaAnTaUy/GLISOxNUyP6f9WnDRlGe5zZ+TeS8YZZo0="
