language: node_js
before_script:
  - cp config.json.default config.json
  - npm install -g bower gulp
  - bower install
  - npm install
script:
  - gulp

addons:
  sauce_connect:
    username: "nschloe"
    access_key: "222f810b-0b68-403d-ba76-6648e1f18eda"
